const ActionTypes = {
  GET_ALL_STUDENTS_REQUEST: "GET_ALL_STUDENTS_REQUEST",
  GET_ALL_STUDENTS_SUCCESS: "GET_ALL_STUDENTS_SUCCESS",
  GET_ALL_STUDENTS_FAIL: "GET_ALL_STUDENTS_FAIL",

  GET_STUDENT_REQUEST: "GET_STUDENT_REQUEST",
  GET_STUDENT_SUCCESS: "GET_STUDENT_SUCCESS",
  GET_STUDENT_FAIL: "GET_STUDENT_FAIL",

  CREATE_STUDENT_REQUEST: "CREATE_STUDENT_REQUEST",
  CREATE_STUDENT_SUCCESS: "CREATE_STUDENT_SUCCESS",
  CREATE_STUDENT_FAIL: "CREATE_STUDENT_FAIL",

  UPDATE_STUDENT_REQUEST: "UPDATE_STUDENT_REQUEST",
  UPDATE_STUDENT_SUCCESS: "UPDATE_STUDENT_SUCCESS",
  UPDATE_STUDENT_FAIL: "UPDATE_STUDENT_FAIL",

  DELETE_STUDENT_REQUEST: "DELETE_STUDENT_REQUEST",
  DELETE_STUDENT_SUCCESS: "DELETE_STUDENT_SUCCESS",
  DELETE_STUDENT_FAIL: "DELETE_STUDENT_FAIL",

  GET_ALL_BOOKS_REQUEST: "GET_ALL_BOOKS_REQUEST",
  GET_ALL_BOOKS_SUCCESS: "GET_ALL_BOOKS_SUCCESS",
  GET_ALL_BOOKS_FAIL: "GET_ALL_BOOKS_FAIL",

  CREATE_BOOK_REQUEST: "CREATE_BOOK_REQUEST",
  CREATE_BOOK_SUCCESS: "CREATE_BOOK_SUCCESS",
  CREATE_BOOK_FAIL: "CREATE_BOOK_FAIL",

  GET_BOOK_REQUEST: "GET_BOOK_REQUEST",
  GET_BOOK_SUCCESS: "GET_BOOK_SUCCESS",
  GET_BOOK_FAIL: "GET_BOOK_FAIL",

  UPDATE_BOOK_REQUEST: "UPDATE_BOOK_REQUEST",
  UPDATE_BOOK_SUCCESS: "UPDATE_BOOK_SUCCESS",
  UPDATE_BOOK_FAIL: "UPDATE_BOOK_FAIL",

  DELETE_BOOK_REQUEST: "DELETE_BOOK_REQUEST",
  DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS",
  DELETE_BOOK_FAIL: "DELETE_BOOK_FAIL",

  BORROW_BOOK_REQUEST: "BORROW_BOOK_REQUEST",
  BORROW_BOOK_SUCCESS: "BORROW_BOOK_SUCCESS",
  BORROW_BOOK_FAIL: "BORROW_BOOK_FAIL",
};

export default ActionTypes;
